name: Deploy to AWS EC2
on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This job will run on a GitHub-hosted runner with Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository to the GitHub Actions runner

      - name: Set up SSH key for EC2
        uses: webfactory/ssh-agent@v0.5.3  # Set up SSH agent for authentication
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # Use the private key stored in GitHub secrets

      - name: Create SSH key file
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_KEY }}
        

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            # SSH into EC2 instance and deploy
            cd /home/ubuntu/pro/
            git pull origin main  # Pull the latest code from the main branch
